# **Limpieza y preparación de datos con pandas**

In [1]:
# Cargamos las librerías
from google.cloud import bigquery
import pandas as pd
import numpy as np
import seaborn as sns

## **Carga de datos (BigQuery Public Dataset program)**

BigQuery es un almacén de datos en la nube con aprendizaje automático integrado.

Comenzamos cargando los datos del [BigQuery Public Dataset Program](https://cloud.google.com/bigquery/public-data), para ello lo primero que haremos es autenticarnos en Google Cloud Platform.

Para acceder a la consola: https://console.cloud.google.com/bigquery?p=bigquery-public-data&d=catalonian_mobile_coverage_eu&page=dataset&authuser=1&project=primeval-beaker-440708-m7&supportedpurview=project&ws=!1m5!1m4!4m3!1sbigquery-public-data!2scatalonian_mobile_coverage_eu!3smobile_data_2015_2017

In [2]:

from google.colab import auth
auth.authenticate_user()
print('Autenticacion exitosa')

Autenticacion exitosa

Leemos los datos de BigQuery y los dejamos en un Dataframe de pandas
Limitamos al lectura a 100000 lineas

In [3]:
project_reader = "saa-tarea1" # Aqui tienes que cambiarlo por tu nombre de proyecto en GCP
project_public = "bigquery-public-data"
dataset_id = "catalonian_mobile_coverage_eu"
table_id = "mobile_data_2015_2017"
bq_client = bigquery.Client(project_reader)
dataset_ref = bigquery.DatasetReference(project_public, dataset_id)
table_ref = dataset_ref.table(table_id)
table = bq_client.get_table(table_ref)
df = bq_client.list_rows(table,max_results=100000).to_dataframe() # Leemos los primeros 100,000 registros
df.head()

,date,hour,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,downloadSpeed,uploadSpeed,postal_code,town_name,position_geom
0,2016-02-22,08:01:04,41.24926,1.74940,4,orange,RACC,0,STATE_IN_SERVICE,None,72.0,9.0,19.0,gps,ON_FOOT,NaN,NaN,082310,Sant Pere de Ribes,POINT(1.7494 41.24926)
1,2016-02-22,08:10:29,41.23588,1.85479,6,orange,RACC,0,STATE_IN_SERVICE,None,31.0,3.0,8.0,gps,ON_FOOT,NaN,NaN,082704,Sitges,POINT(1.85479 41.23588)
2,2016-02-22,07:26:01,41.40321,1.57317,11,orange,RACC,0,STATE_IN_SERVICE,3G,0.0,2.0,14.0,gps,ON_FOOT,NaN,NaN,082883,Torrelles de Foix,POINT(1.57317 41.40321)
3,2016-02-22,20:10:51,41.19022,1.09942,8,orange,RACC,0,STATE_IN_SERVICE,3G,0.5,2.0,8.0,gps,ON_FOOT,NaN,NaN,430424,Castellvell del Camp,POINT(1.09942 41.19022)
4,2016-02-22,08:14:45,41.24853,1.88470,0,orange,RACC,0,STATE_IN_SERVICE,None,36.6,3.0,8.0,gps,IN_VEHICLE,NaN,NaN,082704,Sitges,POINT(1.8847 41.24853)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   date           100000 non-null  dbdate
 1   hour           100000 non-null  dbtime
 2   lat            100000 non-null  float64
 3   long           100000 non-null  float64
 4   signal         100000 non-null  Int64
 5   network        99658 non-null   object
 6   operator       99658 non-null   object
 7   status         100000 non-null  Int64
 8   description    100000 non-null  object
 9   net            97989 non-null   object
 10  speed          100000 non-null  float64
 11  satellites     100000 non-null  float64
 12  precission     100000 non-null  float64
 13  provider       100000 non-null  object
 14  activity       100000 non-null  object
 15  downloadSpeed  0 non-null       float64
 16  uploadSpeed    0 non-null       float64
 17  postal_code    91467 non-null   object
 18  town_name      91467 non-null   object
 19  position_geom  100000 non-null  object
dtypes: Int64(2), dbdate(1), dbtime(1), float64(7), object(9)
memory usage: 15.4+ MB

## Inspeccionar el DataSet

In [5]:
df.head(10)

,date,hour,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,downloadSpeed,uploadSpeed,postal_code,town_name,position_geom
0,2016-02-22,08:01:04,41.24926,1.74940,4,orange,RACC,0,STATE_IN_SERVICE,None,72.0,9.0,19.0,gps,ON_FOOT,NaN,NaN,082310,Sant Pere de Ribes,POINT(1.7494 41.24926)
1,2016-02-22,08:10:29,41.23588,1.85479,6,orange,RACC,0,STATE_IN_SERVICE,None,31.0,3.0,8.0,gps,ON_FOOT,NaN,NaN,082704,Sitges,POINT(1.85479 41.23588)
2,2016-02-22,07:26:01,41.40321,1.57317,11,orange,RACC,0,STATE_IN_SERVICE,3G,0.0,2.0,14.0,gps,ON_FOOT,NaN,NaN,082883,Torrelles de Foix,POINT(1.57317 41.40321)
3,2016-02-22,20:10:51,41.19022,1.09942,8,orange,RACC,0,STATE_IN_SERVICE,3G,0.5,2.0,8.0,gps,ON_FOOT,NaN,NaN,430424,Castellvell del Camp,POINT(1.09942 41.19022)
4,2016-02-22,08:14:45,41.24853,1.88470,0,orange,RACC,0,STATE_IN_SERVICE,None,36.6,3.0,8.0,gps,IN_VEHICLE,NaN,NaN,082704,Sitges,POINT(1.8847 41.24853)
5,2016-02-22,08:29:01,41.31547,2.03456,8,orange,RACC,0,STATE_IN_SERVICE,None,78.9,9.0,9.0,gps,IN_VEHICLE,NaN,NaN,083015,Viladecans,POINT(2.03456 41.31547)
6,2016-02-22,16:15:41,41.82544,1.89583,14,yoigo,YOIGO,0,STATE_IN_SERVICE,3G,0.0,3.0,64.0,gps,STILL,NaN,NaN,081918,Sallent,POINT(1.89583 41.82544)
7,2016-02-22,04:30:28,41.57828,2.13278,3,yoigo,YOIGO,0,STATE_IN_SERVICE,4G,0.0,2.0,96.0,gps,STILL,NaN,NaN,082671,Sentmenat,POINT(2.13278 41.57828)
8,2016-02-22,04:50:59,41.57812,2.13246,3,yoigo,YOIGO,0,STATE_IN_SERVICE,4G,0.1,0.0,96.0,gps,STILL,NaN,NaN,082671,Sentmenat,POINT(2.13246 41.57812)
9,2016-02-22,05:24:38,41.57844,2.13179,3,yoigo,YOIGO,0,STATE_IN_SERVICE,4G,0.1,1.0,96.0,gps,STILL,NaN,NaN,082671,Sentmenat,POINT(2.13179 41.57844)

## Confirmar si hay nulos

In [6]:
df.info()
df.describe()
df.head()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   date           100000 non-null  dbdate
 1   hour           100000 non-null  dbtime
 2   lat            100000 non-null  float64
 3   long           100000 non-null  float64
 4   signal         100000 non-null  Int64
 5   network        99658 non-null   object
 6   operator       99658 non-null   object
 7   status         100000 non-null  Int64
 8   description    100000 non-null  object
 9   net            97989 non-null   object
 10  speed          100000 non-null  float64
 11  satellites     100000 non-null  float64
 12  precission     100000 non-null  float64
 13  provider       100000 non-null  object
 14  activity       100000 non-null  object
 15  downloadSpeed  0 non-null       float64
 16  uploadSpeed    0 non-null       float64
 17  postal_code    91467 non-null   object
 18  town_name      91467 non-null   object
 19  position_geom  100000 non-null  object
dtypes: Int64(2), dbdate(1), dbtime(1), float64(7), object(9)
memory usage: 15.4+ MB

date                  0
hour                  0
lat                   0
long                  0
signal                0
network             342
operator            342
status                0
description           0
net                2011
speed                 0
satellites            0
precission            0
provider              0
activity              0
downloadSpeed    100000
uploadSpeed      100000
postal_code        8533
town_name          8533
position_geom         0
dtype: int64

## Eliminar Columnas sin Utilidad

downloadSpeed y uploadSpeed → 0 valores no nulos → eliminar.

position_geom → redundante, ya tienes lat y long.

In [7]:
df.drop(columns=["downloadSpeed", "uploadSpeed", "position_geom"], inplace=True)

## Fusionar columna de fecha y hora

In [8]:
df["datetime"] = pd.to_datetime(df["date"].astype(str) + " " + df["hour"].astype(str), errors="coerce")
df = df.drop(columns=["date", "hour"])

## Eliminar filas con pequeñas cantidades de nulls (network & operator && net)

In [9]:
df = df.dropna(subset=['network', 'operator', 'net'])

## Rellenar las filas con mayor cantidad de nulls (postal_code & town_name)

In [10]:
df[['postal_code', 'town_name']] = df[['postal_code', 'town_name']].fillna('Desconocido')

## Comprobar nulls hasta este momento

In [11]:
df.isnull().sum()

lat            0
long           0
signal         0
network        0
operator       0
status         0
description    0
net            0
speed          0
satellites     0
precission     0
provider       0
activity       0
postal_code    0
town_name      0
datetime       0
dtype: int64

## Ver el Estado del DataSet

In [12]:
df.head()

,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,postal_code,town_name,datetime
2,41.40321,1.57317,11,orange,RACC,0,STATE_IN_SERVICE,3G,0.0,2.0,14.0,gps,ON_FOOT,082883,Torrelles de Foix,2016-02-22 07:26:01
3,41.19022,1.09942,8,orange,RACC,0,STATE_IN_SERVICE,3G,0.5,2.0,8.0,gps,ON_FOOT,430424,Castellvell del Camp,2016-02-22 20:10:51
6,41.82544,1.89583,14,yoigo,YOIGO,0,STATE_IN_SERVICE,3G,0.0,3.0,64.0,gps,STILL,081918,Sallent,2016-02-22 16:15:41
7,41.57828,2.13278,3,yoigo,YOIGO,0,STATE_IN_SERVICE,4G,0.0,2.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:30:28
8,41.57812,2.13246,3,yoigo,YOIGO,0,STATE_IN_SERVICE,4G,0.1,0.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:50:59

## Categorizar el signal

In [13]:
def clasificar_signal(valor):
    if valor == 0:
        return 1
    elif 1 <= valor <= 5:
        return 2
    elif 6 <= valor <= 10:
        return 3
    elif 11 <= valor <= 15:
        return 4
    elif 16 <= valor <= 25:
        return 5
    else:
        return 0

df['signal'] = df['signal'].apply(clasificar_signal)

In [14]:
# Ver distribución
df['signal'].value_counts(normalize=True)

signal
4    0.287269
5    0.280797
3    0.232368
2    0.124735
0    0.067744
1    0.007087
Name: proportion, dtype: float64

## Ver el Estado del DataSet

In [15]:
df.head()

,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,postal_code,town_name,datetime
2,41.40321,1.57317,4,orange,RACC,0,STATE_IN_SERVICE,3G,0.0,2.0,14.0,gps,ON_FOOT,082883,Torrelles de Foix,2016-02-22 07:26:01
3,41.19022,1.09942,3,orange,RACC,0,STATE_IN_SERVICE,3G,0.5,2.0,8.0,gps,ON_FOOT,430424,Castellvell del Camp,2016-02-22 20:10:51
6,41.82544,1.89583,4,yoigo,YOIGO,0,STATE_IN_SERVICE,3G,0.0,3.0,64.0,gps,STILL,081918,Sallent,2016-02-22 16:15:41
7,41.57828,2.13278,2,yoigo,YOIGO,0,STATE_IN_SERVICE,4G,0.0,2.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:30:28
8,41.57812,2.13246,2,yoigo,YOIGO,0,STATE_IN_SERVICE,4G,0.1,0.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:50:59

## Categorizar el Network

In [16]:
df['network'].value_counts()

network
movistar                         40277
orange                           26232
vodafone                         22648
yoigo                             2912
MetroPCS                          1131
Orange SP                          706
Orange F                           389
Telefonica Moviles Espana          354
null                               329
France Telcom Espana SA            327
TICAE                              297
GETESA                             247
F SFR                              220
T-Mobile                           191
VIVO                               168
MOBILAND                           159
I WIND                             141
Lycamobile                         110
Eroski Movil                       109
Lowi                               101
ION MOBILE                          77
LlamaYA                             71
P TMN                               66
F-Bouygues Telecom                  66
GurbTec                             54
GNQ01                               42
ETICOM SC                           34
o2 - de                             31
T-Mobile A                          29
Nom├®s trucades d'emerg├¿ncia       23
yallo                               21
MASMovil                            19
F Bouygues                          17
Swisscom                            17
Vodafone Spain                      15
Solo llamadas de emergencia          8
PARLEM                               6
Sense servei.                        1
vodafone IT                          1
France Telecom Espa├▒a SA            1
Name: count, dtype: int64

In [17]:

map_network = {
    # Movistar
    'movistar': 'Movistar',
    'Telefonica Moviles Espana': 'Movistar',
    'France Telecom España SA': 'Movistar',
    'France Telecom Espa├▒a SA': 'Movistar',

    # Orange
    'orange': 'Orange',
    'Orange SP': 'Orange',
    'Orange F': 'Orange',
    'France Telcom Espana SA': 'Orange',
    'F SFR': 'Orange',
    'F-Bouygues Telecom': 'Orange',
    'F Bouygues': 'Orange',

    # Vodafone
    'vodafone': 'Vodafone',
    'Vodafone Spain': 'Vodafone',
    'vodafone IT': 'Vodafone',
    'Lowi': 'Vodafone',

    # Yoigo / Grupo MasMovil
    'yoigo': 'Grupo MasMovil',
    'MASMovil': 'Grupo MasMovil',
    'Parlem': 'Grupo MasMovil',
    'PARLEM': 'Grupo MasMovil',
    'Lycamobile': 'Grupo MasMovil',
    'LlamaYA': 'Grupo MasMovil',
    'ION MOBILE': 'Grupo MasMovil',
    'Eroski Movil': 'Grupo MasMovil',
    'GurbTec': 'Grupo MasMovil',
    'ETICOM SC': 'Grupo MasMovil',
    'TICAE': 'Grupo MasMovil',
    'GETESA': 'Grupo MasMovil',

    # Otros / Internacionales
    'T-Mobile': 'Otros',
    'T-Mobile A': 'Otros',
    'VIVO': 'Otros',
    'I WIND': 'Otros',
    'yallo': 'Otros',
    'Swisscom': 'Otros',
    'MetroPCS': 'Otros',
    'P TMN': 'Otros',
    'GNQ01': 'Otros',
    'MOBILAND': 'Otros',
    'o2 - de': 'Otros',

    # Emergencia / sin servicio
    'Solo llamadas de emergencia': 'Sin servicio',
    "Nom├®s trucades d'emerg├¿ncia": 'Sin servicio',
    'Sense servei.': 'Sin servicio',
    'Sin servicio': 'Sin servicio',

    # Nulos explícitos
    'null': np.nan
}

df['network'] = df['network'].replace(map_network)

df['network'].value_counts()

network
Movistar          40632
Orange            27957
Vodafone          22765
Grupo MasMovil     3936
Otros              1996
Sin servicio         32
Name: count, dtype: int64

In [18]:
df = df.dropna(subset=['network'])

In [19]:
df.head()

,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,postal_code,town_name,datetime
2,41.40321,1.57317,4,Orange,RACC,0,STATE_IN_SERVICE,3G,0.0,2.0,14.0,gps,ON_FOOT,082883,Torrelles de Foix,2016-02-22 07:26:01
3,41.19022,1.09942,3,Orange,RACC,0,STATE_IN_SERVICE,3G,0.5,2.0,8.0,gps,ON_FOOT,430424,Castellvell del Camp,2016-02-22 20:10:51
6,41.82544,1.89583,4,Grupo MasMovil,YOIGO,0,STATE_IN_SERVICE,3G,0.0,3.0,64.0,gps,STILL,081918,Sallent,2016-02-22 16:15:41
7,41.57828,2.13278,2,Grupo MasMovil,YOIGO,0,STATE_IN_SERVICE,4G,0.0,2.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:30:28
8,41.57812,2.13246,2,Grupo MasMovil,YOIGO,0,STATE_IN_SERVICE,4G,0.1,0.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:50:59

## Categorizar el operator

In [20]:
df['operator'].value_counts()

operator
Movistar                         30053
vodafone ES                      21746
Orange                           19285
movistar                          6053
JAZZTEL                           3761
pepephone                         3624
RACC                              1534
YOIGO                             1467
Yoigo                             1445
MetroPCS                          1131
simyo                             1097
Vodafone ES                        785
Orange SP                          706
Orange F                           389
Telefonica Moviles Espana          354
adamo                              352
France Telcom Espana SA            327
ONO                                316
TICAE                              297
GETESA                             247
Tuenti                             231
F SFR                              220
Lowi                               218
T-Mobile                           191
VIVO                               168
MOBILAND                           159
I WIND                             141
Lycamobile                         110
Eroski Movil                       109
PARLEM                             100
ION MOBILE                          77
LlamaYA                             71
P TMN                               66
F-Bouygues Telecom                  66
MASMOVIL                            61
GurbTec                             54
Jazztel                             48
GNQ01                               42
ETICOM SC                           34
o2 - de                             31
T-Mobile A                          29
Nom├®s trucades d'emerg├¿ncia       23
yallo                               21
MASMovil                            19
F Bouygues                          17
Swisscom                            17
Vodafone Spain                      15
Solo llamadas de emergencia          8
Sense servei.                        1
vodafone IT                          1
France Telecom Espa├▒a SA            1
Name: count, dtype: int64

In [21]:
map_operator = {
    # Movistar
    'Movistar': 'Movistar',
    'movistar': 'Movistar',
    'Telefonica Moviles Espana': 'Movistar',
    'France Telecom Espa├▒a SA': 'Movistar',

    # Orange
    'Orange': 'Orange',
    'Orange SP': 'Orange',
    'Orange F': 'Orange',
    'F SFR': 'Orange',
    'F-Bouygues Telecom': 'Orange',
    'F Bouygues': 'Orange',
    'France Telcom Espana SA': 'Orange',

    # Vodafone
    'vodafone ES': 'Vodafone',
    'Vodafone ES': 'Vodafone',
    'vodafone IT': 'Vodafone',
    'Vodafone Spain': 'Vodafone',
    'Lowi': 'Vodafone',
    'vodafone': 'Vodafone',

    # Grupo MasMovil
    'Yoigo': 'Grupo MasMovil',
    'yoigo': 'Grupo MasMovil',
    'MASMOVIL': 'Grupo MasMovil',
    'MASMovil': 'Grupo MasMovil',
    'PARLEM': 'Grupo MasMovil',
    'Parlem': 'Grupo MasMovil',
    'Lycamobile': 'Grupo MasMovil',
    'LlamaYA': 'Grupo MasMovil',
    'ION MOBILE': 'Grupo MasMovil',
    'Eroski Movil': 'Grupo MasMovil',
    'GurbTec': 'Grupo MasMovil',
    'ETICOM SC': 'Grupo MasMovil',
    'TICAE': 'Grupo MasMovil',
    'GETESA': 'Grupo MasMovil',
    'Jazztel': 'Grupo MasMovil',

    # Otros / Internacionales
    'T-Mobile': 'Otros',
    'T-Mobile A': 'Otros',
    'VIVO': 'Otros',
    'I WIND': 'Otros',
    'yallo': 'Otros',
    'Swisscom': 'Otros',
    'MetroPCS': 'Otros',
    'P TMN': 'Otros',
    'GNQ01': 'Otros',
    'MOBILAND': 'Otros',
    'o2 - de': 'Otros',

    # Emergencia / sin servicio
    'Solo llamadas de emergencia': 'Sin servicio',
    'Nom├®s trucades d\'emerg├¿ncia': 'Sin servicio',
    'Sense servei.': 'Sin servicio',
    'RACC': 'Sin servicio',

    # Nulos explícitos
    'null': np.nan
}

df['operator'] = df['operator'].map(map_operator)

In [22]:
df['operator'].value_counts()

operator
Movistar          36461
Vodafone          22765
Orange            21010
Grupo MasMovil     2672
Otros              1996
Sin servicio       1566
Name: count, dtype: int64

In [23]:
df['operator'].isnull().sum()

np.int64(10848)

#Tratar de inferir el valor según su network, sino asignarle desconocido

In [24]:
df.loc[df['operator'].isna(), 'operator'] = df['network']
df['operator'] = df['operator'].fillna('Desconocido')

In [25]:
df['operator'].value_counts()

operator
Movistar          40632
Orange            26220
Vodafone          22765
Grupo MasMovil     4139
Otros              1996
Sin servicio       1566
Name: count, dtype: int64

## Asignar un valor númerico a la categoría de network & operator

In [26]:
network_category = {
    'Sin servicio': 0,
    'Movistar': 1,
    'Orange': 2,
    'Vodafone': 3,
    'Grupo MasMovil': 4,
    'Otros': 5
}

df['network'] = df['network'].map(network_category)

In [27]:
operator_category = {
    'Sin servicio': 0,
    'Movistar': 1,
    'Orange': 2,
    'Vodafone': 3,
    'Grupo MasMovil': 4,
    'Otros': 5
}

df['operator'] = df['operator'].map(operator_category)

In [28]:
df['operator'].value_counts()

operator
1    40632
2    26220
3    22765
4     4139
5     1996
0     1566
Name: count, dtype: int64

In [29]:
df.head()

,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,postal_code,town_name,datetime
2,41.40321,1.57317,4,2,0,0,STATE_IN_SERVICE,3G,0.0,2.0,14.0,gps,ON_FOOT,082883,Torrelles de Foix,2016-02-22 07:26:01
3,41.19022,1.09942,3,2,0,0,STATE_IN_SERVICE,3G,0.5,2.0,8.0,gps,ON_FOOT,430424,Castellvell del Camp,2016-02-22 20:10:51
6,41.82544,1.89583,4,4,4,0,STATE_IN_SERVICE,3G,0.0,3.0,64.0,gps,STILL,081918,Sallent,2016-02-22 16:15:41
7,41.57828,2.13278,2,4,4,0,STATE_IN_SERVICE,4G,0.0,2.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:30:28
8,41.57812,2.13246,2,4,4,0,STATE_IN_SERVICE,4G,0.1,0.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:50:59

In [30]:
df['description'].value_counts()

description
STATE_EMERGENCY_ONLY    87282
STATE_IN_SERVICE         9915
STATE_POWER_OFF           120
STATE_OUT_OF_SERVICE        1
Name: count, dtype: int64

## Categorizar la variable description

In [31]:
map_description = {
    'STATE_IN_SERVICE': 1,
    'STATE_EMERGENCY_ONLY': 0,
    'STATE_POWER_OFF': -1,
    'STATE_OUT_OF_SERVICE': -2
}

df['description'] = df['description'].map(map_description)

In [32]:
df['description'].value_counts()

description
 0    87282
 1     9915
-1      120
-2        1
Name: count, dtype: int64

In [33]:
df.head()

,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,postal_code,town_name,datetime
2,41.40321,1.57317,4,2,0,0,1,3G,0.0,2.0,14.0,gps,ON_FOOT,082883,Torrelles de Foix,2016-02-22 07:26:01
3,41.19022,1.09942,3,2,0,0,1,3G,0.5,2.0,8.0,gps,ON_FOOT,430424,Castellvell del Camp,2016-02-22 20:10:51
6,41.82544,1.89583,4,4,4,0,1,3G,0.0,3.0,64.0,gps,STILL,081918,Sallent,2016-02-22 16:15:41
7,41.57828,2.13278,2,4,4,0,1,4G,0.0,2.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:30:28
8,41.57812,2.13246,2,4,4,0,1,4G,0.1,0.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:50:59

In [34]:
df['net'].value_counts()

net
4G    41561
3G    36305
2G    19452
Name: count, dtype: int64

## Categorizar la variable net

In [35]:
map_net = {
    '2G': 2,
    '3G': 3,
    '4G': 4
}

df['net'] = df['net'].map(map_net)

In [36]:
df['net'].value_counts()

net
4    41561
3    36305
2    19452
Name: count, dtype: int64

In [37]:
df.head()

,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,postal_code,town_name,datetime
2,41.40321,1.57317,4,2,0,0,1,3,0.0,2.0,14.0,gps,ON_FOOT,082883,Torrelles de Foix,2016-02-22 07:26:01
3,41.19022,1.09942,3,2,0,0,1,3,0.5,2.0,8.0,gps,ON_FOOT,430424,Castellvell del Camp,2016-02-22 20:10:51
6,41.82544,1.89583,4,4,4,0,1,3,0.0,3.0,64.0,gps,STILL,081918,Sallent,2016-02-22 16:15:41
7,41.57828,2.13278,2,4,4,0,1,4,0.0,2.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:30:28
8,41.57812,2.13246,2,4,4,0,1,4,0.1,0.0,96.0,gps,STILL,082671,Sentmenat,2016-02-22 04:50:59

In [38]:
df['provider'].value_counts()

provider
gps        84125
fused      13192
network        1
Name: count, dtype: int64

## Categorizar la variable provider

In [39]:
df['provider'] = df['provider'].replace({'network': 'fused'}) # El valor network aparece una vez, asi que tiene irrelevancia

map_provider = {
    'gps': 0,       # mayor precisión
    'fused': 1      # menor precisión
}
df['provider'] = df['provider'].map(map_provider)

In [40]:
df['provider'].value_counts()

provider
0    84125
1    13193
Name: count, dtype: int64

In [41]:
df.head()

,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,postal_code,town_name,datetime
2,41.40321,1.57317,4,2,0,0,1,3,0.0,2.0,14.0,0,ON_FOOT,082883,Torrelles de Foix,2016-02-22 07:26:01
3,41.19022,1.09942,3,2,0,0,1,3,0.5,2.0,8.0,0,ON_FOOT,430424,Castellvell del Camp,2016-02-22 20:10:51
6,41.82544,1.89583,4,4,4,0,1,3,0.0,3.0,64.0,0,STILL,081918,Sallent,2016-02-22 16:15:41
7,41.57828,2.13278,2,4,4,0,1,4,0.0,2.0,96.0,0,STILL,082671,Sentmenat,2016-02-22 04:30:28
8,41.57812,2.13246,2,4,4,0,1,4,0.1,0.0,96.0,0,STILL,082671,Sentmenat,2016-02-22 04:50:59

In [42]:
df['activity'].value_counts()

activity
IN_VEHICLE    47937
ON_FOOT       20150
STILL         12723
TILTING        8581
UNKNOWN        6432
ON_BICYCLE     1495
Name: count, dtype: int64

## Categorizar la variable Activity

In [43]:
# Se pueden hacer varias cosas con la variable UNKNOWN -> Mantenerlos, Remplazarlos por la categoría más repetida (IN_VEHICLE), Eliminar las Filas (6%)

map_activity = {
    'IN_VEHICLE': 0,
    'ON_FOOT': 1,
    'STILL': 2,
    'TILTING': 3,
    'ON_BICYCLE': 4,
    'UNKNOWN': 5
}

df['activity'] = df['activity'].map(map_activity)

# Explorar la opción de One-hot encoding
# df = pd.get_dummies(df, columns=['activity'], prefix='activity')

In [44]:
df['activity'].value_counts()

activity
0    47937
1    20150
2    12723
3     8581
5     6432
4     1495
Name: count, dtype: int64

In [45]:
df.head()

,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,postal_code,town_name,datetime
2,41.40321,1.57317,4,2,0,0,1,3,0.0,2.0,14.0,0,1,082883,Torrelles de Foix,2016-02-22 07:26:01
3,41.19022,1.09942,3,2,0,0,1,3,0.5,2.0,8.0,0,1,430424,Castellvell del Camp,2016-02-22 20:10:51
6,41.82544,1.89583,4,4,4,0,1,3,0.0,3.0,64.0,0,2,081918,Sallent,2016-02-22 16:15:41
7,41.57828,2.13278,2,4,4,0,1,4,0.0,2.0,96.0,0,2,082671,Sentmenat,2016-02-22 04:30:28
8,41.57812,2.13246,2,4,4,0,1,4,0.1,0.0,96.0,0,2,082671,Sentmenat,2016-02-22 04:50:59

## ¿Qué hacer con las demás?

| Variable      | Qué hacer                                                                   | Resultado                 |
| ------------- | --------------------------------------------------------------------------- | ------------------------- |
| `postal_code` | Usar solo los **2 primeros dígitos** o eliminar si no es relevante          | `postal_area`             |
| `town_name`   | Agrupar en principales ciudades y resto como `"Otros"`                      | `town_name_simplified`    |
| `datetime`    | Convertir a datetime, extraer `hour`, `weekday`, `month`, eliminar original | columnas numéricas útiles |

NOTAS:

1. ELIMINAR EL TOWN_NAME
2. EL DATA TIME PUEDE SERVIRNOS PARA VER EN QUE HORA, DÍA O DEMÁS HAY MAS TRAFICO
3. El POSTAL_CODE dejarlo
4. Posteriormente con la latitud y longitud sacaremos datos de posicionamiento

## Eliminar la categoría town_name

In [46]:
df.drop(columns=["town_name"], inplace=True)

## Extraer información importante de datatime

In [47]:
df['datetime'] = pd.to_datetime(df['datetime'], errors='coerce')

df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
df['day'] = df['datetime'].dt.day
df['hour'] = df['datetime'].dt.hour
df['weekday'] = df['datetime'].dt.weekday  # 0 = lunes, 6 = domingo

df = df.drop(columns=['datetime'])

df.head()

,lat,long,signal,network,operator,status,description,net,speed,satellites,precission,provider,activity,postal_code,year,month,day,hour,weekday
2,41.40321,1.57317,4,2,0,0,1,3,0.0,2.0,14.0,0,1,082883,2016,2,22,7,0
3,41.19022,1.09942,3,2,0,0,1,3,0.5,2.0,8.0,0,1,430424,2016,2,22,20,0
6,41.82544,1.89583,4,4,4,0,1,3,0.0,3.0,64.0,0,2,081918,2016,2,22,16,0
7,41.57828,2.13278,2,4,4,0,1,4,0.0,2.0,96.0,0,2,082671,2016,2,22,4,0
8,41.57812,2.13246,2,4,4,0,1,4,0.1,0.0,96.0,0,2,082671,2016,2,22,4,0